language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: ./SimpleSql/SimpleSql.sln
before_install:
  - dotnet --version
script:
  - dotnet restore ./SimpleSql/SimpleSql/SimpleSql.csproj
  - dotnet pack ./SimpleSql/SimpleSql/SimpleSql.csproj -c Release