language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
solution: ./SimpleSql/SimpleSql.sln
before_install:
  - dotnet --version
script:
  - dotnet restore ./SimpleSql/SimpleSql/SimpleSql.csproj
  - dotnet pack ./SimpleSql/SimpleSql/SimpleSql.csproj -c Release
  - cd ./SimpleSql/SimpleSql/bin/Release/&&dotnet nuget push *.nupkg -k 719a7151-cdec-4c97-af59-7b34f4a5081e -s https://www.nuget.org/api/v2/package